# Generated by Django 3.2 on 2022-01-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('homepage', models.URLField()),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('runtime', models.IntegerField()),
            ],
        ),
    ]
