# Generated by Django 3.2 on 2022-01-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
